### PR TITLE
Convert component to Typescript

### PR DESCRIPTION
**Pull request by denis-mludek**
Just sharing this if anyone, like me, is using it in a project with Typescript

When Generic Component will be available with Svelte, it will be even better :)  (instead of a props `items: any[]`)

### CODE REVIEW

**Comment by Himujjal** [comment]
@Rich-Harris can you please merge this PR?

**Comment by dummdidumm** [comment]
This is a bad idea, because you now force every user of this package to setup a preprocessor to transpile TS to JS. What you really want is a type definition file named `VirtualList.svelte.d.ts` and provide typings in there. Newer versions of `svelte-check` and the VS Code extension will pick that up.

**Comment by benmccann** [comment]
Can't the preprocessing be done in this component so that users don't need to do the conversion? I think that's either what `svelte-kit package` does or what it was planned to have it do eventually

**Comment by dummdidumm** [comment]
It can, but the point of this PR is to have better typings for devs using the Svelte file, not for the devs authoring this repo. And the easiest way to achieve this is to create a handwritten `.d.ts` file.

**Comment by antony** [comment]
Aside from all the above comments, this PR completely changes the code style (specifically indents, haven't looked at the rest), so is, for that reason alone, untenable.

**Comment by Himujjal** [comment]
Seems like `.d.ts` is the better way out rather than converting to TypeScript? Will the authors accept another PR for the same?

**Comment by dummdidumm** [comment]
Can't approve here officially but I would accept it. Just @ me in the PR so I can take a look

**Comment by stalkerg** [comment]
Yes, I am using it a lot in a pure JS environment, I don't want to add TS dependency for my projects.

**Pull request closed without merging**
